# whitelist
branches:
  only:
    - master
    - /^tickets\/.*$/

sudo: false

services:
  - docker

language: c++

before_install:
  # Set up parameters for containers deployment
  - cp ./admin/tools/docker/deployment/travis/env.sh ./admin/tools/docker/deployment/localhost/env.sh
  # While running 3_build-git-image.sh [option] <local-path>, <local-path> has to contain a git repository
  # whose current commit is a branch HEAD
  - git checkout -b travis
  - export VERSION="qserv/qserv:$(git rev-parse --short HEAD)"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export BRANCH_IMAGE="qserv/qserv:$BRANCH"

install:
  # Retrieve container with Qserv dependencies
  - docker pull qserv/qserv:dev

script:
  - echo "Building and testing $VERSION (alias $BRANCH_IMAGE) and related master and worker images"
  - ./admin/tools/docker/3_build-git-image.sh -L -T "$VERSION" "$PWD"
  - ./admin/tools/docker/4_build-configured-images.sh -L -i "$VERSION"
  - ./admin/tools/docker/deployment/localhost/run-multinode-tests.sh

notifications:
  slack:
    secure: eRFF9b5XJbZcyfxMojWTOB4bwWUVJf0CRaOYnCsV7cMCW5BwrDRwC+8tpZyEbetyici7XdFN33kW4rRp9UFfOCIsLS5fMJEKgjvgD0ybucThPsBqLE2VDzDzA6dUji7CATCPUtvoJEymM41pnvDZbXmtalipYzZJMPNXHyE8Yy0=

after_success:
  - echo "Push $VERSION and associated master, worker images to Docker Hub"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push "$VERSION"
  - docker push "${VERSION}_master"
  - docker push "${VERSION}_worker"
  - echo "Add tag $BRANCH to images above and push to Docker Hub"
  - docker tag "$VERSION" "$BRANCH_IMAGE"
  - docker tag "${VERSION}_master" "${BRANCH_IMAGE}_master"
  - docker tag "${VERSION}_worker" "${BRANCH_IMAGE}_worker"
  - docker push "qserv/qserv:$BRANCH"
  - docker push "${BRANCH_IMAGE}_master"
  - docker push "${BRANCH_IMAGE}_worker"

